name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  buildnpush:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Docker Hub Login
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the docker image
      run: docker build -t first-app:latest .
    - name: Tag the image
      run: docker tag first-app:latest jawadc/first-app:latest
    - name: Push the image
      run: docker push jawadc/first-app:latest